AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple API with Lambda + DynamoDB

Globals:
  Function:
    Runtime: python3.13
    Timeout: 10
    MemorySize: 128

Resources:

  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Notes  
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/notes/
      Handler: app.lambda_handler
      Environment:
        Variables:
          TABLE_NAME: !Ref ItemsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        GetItems:
          Type: Api
          Properties:
            Path: /notes
            Method: GET
        CreateItem:
          Type: Api
          Properties:
            Path: /notes
            Method: POST